### ISSUE TITLE
Create a table automatically if missing

### ISSUE THREAD

**Issue by HelenMel** [aiven/bigquery-connector-for-apache-flink#13]
# What is currently missing?

Currently, a table should exist in BQ to start writing into a table. This means that the customer had to manually specify a table and a schema if it doesn't exist. However, event types and names already represent a table schema, required to create a table. That is why it would be much easier if there will be a parameter to create a tabl automatically if it doesn't exist

# Is this a feature you would work on yourself?

* [ ] I plan to open a pull request for this feature

**Comment by snuyanzin** [comment]
i guess there are still some open questions which are not covered
e.g. nested arrays, arrays with nullable datatypes which are not supported by BigQuery 
however there are some WAs to support it (may be need to discuss separately if there is any interest in that)
